#we use java
language: java

#we add the java development kit (jdk)
jdk:
- openjdk8

# SonarCloud
addons:
  sonarcloud:
    organization: "jeanpaulyazbek"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

before_install:
- mvn clean

after_success:
- bash <(curl -s https://codecov.io/bash)
# SonarCloud
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
